### ISSUE TITLE
CCID support for Android

### ISSUE THREAD

**Issue by flyingsaucer88** [LudovicRousseau/CCID#143]
Hello,

Is there some support for this library on Android OS?

If so, please advise.

**Comment by LudovicRousseau** [comment]
No support for Android yet.
But that may be possible.

**Comment by ndshah88** [comment]
Any thoughts or steps that can be followed to port this library on Android?

This is the same thing as libccid. Correct?

**Comment by ndshah88** [comment]
Or the ARM architecture in general?

**Comment by LudovicRousseau** [comment]
This code is already working fine on ARM.
For example it is included by Apple on macOS since years and works fine on M1, M2, M3 chips.
It is also available as Debian package for arm64, armel, armhf https://packages.debian.org/sid/libccid

In general the package name is libccid. So I guess the answer to your question is: yes

To continue the discussion please contact me by email. See https://blog.apdu.fr/articles/about_me/
